import React, { createContext, useContext, useState } from 'react';

// Supported languages
export type Language = 'en' | 'hi';

// Language labels
export const languageLabels: Record<Language, string> = {
  en: 'English',
  hi: 'हिन्दी (Hindi)'
};

// Language Context Type
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  translate: (key: string) => string;
}

// Create the context
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// State name translations for each language
const stateTranslations: Record<Language, Record<string, string>> = {
  en: {
    'andhra-pradesh': 'Andhra Pradesh',
    'assam': 'Assam',
    'bihar': 'Bihar',
    'gujarat': 'Gujarat',
    'haryana': 'Haryana',
    'karnataka': 'Karnataka',
    'kerala': 'Kerala',
    'madhya-pradesh': 'Madhya Pradesh',
    'maharashtra': 'Maharashtra',
    'odisha': 'Odisha',
    'punjab': 'Punjab',
    'rajasthan': 'Rajasthan',
    'tamil-nadu': 'Tamil Nadu',
    'telangana': 'Telangana',
    'uttar-pradesh': 'Uttar Pradesh',
    'west-bengal': 'West Bengal',
    Delhi: 'Delhi',
    Mumbai: 'Mumbai',
    Bangalore: 'Bangalore',
    Kolkata: 'Kolkata',
    Chennai: 'Chennai',
    'guntur-mandi': 'Guntur Mandi, Andhra Pradesh',
    'vijayawada-mandi': 'Vijayawada Mandi, Andhra Pradesh',
    'nashik-mandi': 'Nashik Mandi, Maharashtra',
    'aurangabad-mandi': 'Aurangabad Mandi, Maharashtra',
    'ludhiana-mandi': 'Ludhiana Mandi, Punjab',
    'amritsar-mandi': 'Amritsar Mandi, Punjab',
    'lucknow-mandi': 'Lucknow Mandi, Uttar Pradesh',
    'agra-mandi': 'Agra Mandi, Uttar Pradesh',
    'hubli-mandi': 'Hubli Mandi, Karnataka',
    'rajkot-mandi': 'Rajkot Mandi, Gujarat',
    'ahmedabad-mandi': 'Ahmedabad Mandi, Gujarat',
  },
  hi: {
    'andhra-pradesh': 'आंध्र प्रदेश',
    'assam': 'असम',
    'bihar': 'बिहार',
    'gujarat': 'गुजरात',
    'haryana': 'हरियाणा',
    'karnataka': 'कर्नाटक',
    'kerala': 'केरल',
    'madhya-pradesh': 'मध्य प्रदेश',
    'maharashtra': 'महाराष्ट्र',
    'odisha': 'ओडिशा',
    'punjab': 'पंजाब',
    'rajasthan': 'राजस्थान',
    'tamil-nadu': 'तमिलनाडु',
    'telangana': 'तेलंगाना',
    'uttar-pradesh': 'उत्तर प्रदेश',
    'west-bengal': 'पश्चिम बंगाल',
    Delhi: 'दिल्ली',
    Mumbai: 'मुंबई',
    Bangalore: 'बैंगलोर',
    Kolkata: 'कोलकाता',
    Chennai: 'चेन्नई',
    'guntur-mandi': 'गुंटूर मंडी, आंध्र प्रदेश',
    'vijayawada-mandi': 'विजयवाड़ा मंडी, आंध्र प्रदेश',
    'nashik-mandi': 'नासिक मंडी, महाराष्ट्र',
    'aurangabad-mandi': 'औरंगाबाद मंडी, महाराष्ट्र',
    'ludhiana-mandi': 'लुधियाना मंडी, पंजाब',
    'amritsar-mandi': 'अमृतसर मंडी, पंजाब',
    'lucknow-mandi': 'लखनऊ मंडी, उत्तर प्रदेश',
    'agra-mandi': 'आगरा मंडी, उत्तर प्रदेश',
    'hubli-mandi': 'हुबली मंडी, कर्नाटक',
    'rajkot-mandi': 'राजकोट मंडी, गुजरात',
    'ahmedabad-mandi': 'अहमदाबाद मंडी, गुजरात',
  }
};

// Translation dictionaries for different languages
const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'Mitra',
    tagline: 'Your Farming Companion',
    selectCrop: 'Select Crop',
    selectRegion: 'Select Region',
    selectSeason: 'Select Season',
    dashboard: 'Dashboard',
    marketPrices: 'Market Prices',
    weather: 'Weather',
    cropAdvisory: 'Crop Advisory',
    settings: 'Settings',
    settingsTitle: 'Customize Your Experience',
    settingsSubtitle: 'Personalize the app according to your preferences',
    profile: 'Profile',
    editProfile: 'Edit Profile',
    languageSettings: 'Language Settings',
    languageDescription: 'Choose your preferred language',
    appearance: 'Appearance',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    notifications: 'Notifications',
    weatherAlertsDescription: 'Get alerts about weather changes and forecasts',
    priceAlerts: 'Price Alerts',
    priceAlertsDescription: 'Receive notifications when crop prices change significantly',
    advisories: 'Advisories',
    advisoriesDescription: 'Get timely farming advice and recommendations',
    newsUpdates: 'News Updates',
    newsUpdatesDescription: 'Stay updated with agricultural news and policies',
    offlineMode: 'Offline Mode',
    offlineModeDescription: 'Access important information without internet',
    location: 'Location',
    autoLocation: 'Auto Location',
    autoLocationDescription: 'Automatically detect your location',
    defaultLocation: 'Default Location',
    defaultLocationDescription: 'Set your preferred location',
    dataUsage: 'Data Usage',
    dataUsageDescription: 'Manage how the app uses your data',
    clearData: 'Clear Data',
    clearDataDescription: 'Delete cached data and reset preferences',
    saveSettings: 'Save Settings',
    themeChanged: 'Theme changed to',
    notificationsEnabled: 'notifications enabled',
    offlineModeEnabled: 'Offline mode enabled',
    offlineModeDisabled: 'Offline mode disabled',
    dataClearedSuccess: 'Data cleared successfully',
    settingsSaved: 'Settings saved successfully',
    balanced: 'Balanced',
    highQuality: 'High Quality',
    lowData: 'Low Data',
    logout: 'Logout',
    language: 'Language',
    download: 'Download',
    offline: 'Offline Access',
    login: 'Login',
    register: 'Register',
    rice: 'Rice',
    wheat: 'Wheat',
    cotton: 'Cotton',
    pulses: 'Pulses',
    vegetables: 'Vegetables',
    fruits: 'Fruits',
    kharif: 'Kharif',
    rabi: 'Rabi',
    zaid: 'Zaid',
    currentPrice: 'Current Price',
    forecast: 'Forecast',
    todayTemp: 'Today\'s Temperature',
    rainfall: 'Rainfall',
    humidity: 'Humidity',
    soilMoisture: 'Soil Moisture',
    cropSuggestions: 'Crop Care Suggestions',
    irrigation: 'Irrigation',
    pestControl: 'Pest Control',
    fertilizers: 'Fertilizers',
    welcomeMessage: 'Welcome to Mitra, your personalized farming companion',
    submitButton: 'Submit',
    saveButton: 'Save',
    cancelButton: 'Cancel',
    recentUpdates: 'Recent Updates',
    todaysAdvice: 'Today\'s Advice',
    dailyAdvice: 'Water your crops today for optimal growth and maintenance.',
    welcomeBack: 'Welcome back',
    viewMore: 'View More',
    nearbyMandis: 'Nearby Mandis',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    firstName: 'First Name',
    lastName: 'Last Name',
    forgotPassword: 'Forgot Password?',
    signingIn: 'Signing In...',
    creating: 'Creating Account...',
    noAccount: 'Don\'t have an account?',
    alreadyHaveAccount: 'Already have an account?',
    backToHome: 'Back to Home',
    phoneNumber: 'Phone Number',
    verifyPhone: 'Verify Phone',
    enterOTP: 'Enter OTP',
    verifyOTP: 'Verify OTP',
    verificationCode: 'Verification Code',
    resendOTP: 'Resend OTP',
    otpSent: 'OTP sent to your phone',
    verifyPhoneDescription: 'Enter the 6-digit code sent to your phone',
    selectState: 'Select State',
    stateSearch: 'Search states',
    allCrops: 'All Crops',
    fromYesterday: 'from yesterday',
    marketPricesTitle: 'Real-time Mandi Prices',
    marketPricesSubtitle: 'Get the latest crop prices from local mandis',
    cropAdvisoryTitle: 'Crop Advisory',
    cropAdvisorySubtitle: 'Get personalized advice for your crops',
    getAdvisory: 'Get Advisory',
    loading: 'Loading...',
    selectAllFields: 'Please select all fields',
    advisoryLoaded: 'Advisory loaded successfully',
    irrigationAdvice: 'Maintain 5cm water level in the field. Drain out excess water if any.',
    pestControlAdvice: 'Monitor for leaf folder and stem borer. Apply neem-based pesticides if infestation is observed.',
    fertilizerAdvice: 'Apply second dose of nitrogen (urea) after 3 weeks of transplanting.',
    bestPracticesAdvice: 'Ensure proper spacing between plants for optimal growth.',
    warnings: 'Warnings',
    seasonalCalendar: 'Seasonal Calendar',
    calendarComingSoon: 'Calendar feature coming soon',
    expertTips: 'Expert Tips',
    soilHealth: 'Soil Health',
    waterManagement: 'Water Management',
    integratedPestManagement: 'Integrated Pest Management',
    soilHealthTip: 'Regular soil testing helps maintain optimal nutrient levels',
    waterManagementTip: 'Efficient irrigation saves water and prevents waterlogging',
    pestManagementTip: 'Use natural pest control methods when possible',
    howToUse: 'How to Use',
    howToUseStep1: 'Select your crop from the dropdown',
    howToUseStep2: 'Choose your region',
    howToUseStep3: 'Select the current growing season',
    marketTrends: 'Market Trends',
    knowYourMarket: 'Know Your Market',
    marketInfoDescription: 'Understanding market dynamics is crucial for farmers. Here\'s what you need to know.',
    mandis: 'Mandis',
    mandisDescription: 'Agricultural markets where farmers can sell their produce directly to buyers',
    priceFluctuations: 'Price Fluctuations',
    priceFluctuationsDescription: 'Market prices change based on supply, demand, and seasonal factors',
    msp: 'Minimum Support Price',
    mspDescription: 'Government-set floor price for select crops to protect farmers from market volatility',
    comingSoon: 'Coming Soon',
    loginRequired: 'Login required to access features',
    homeLoginPrompt: 'Sign in to access all features',
    offlineDescription: 'Access critical information even without internet connection',
    downloadApp: 'Download App',
    selectLanguage: 'Select Language',
    weatherForecast: 'Your Local Weather',
    weatherSubtitle: 'Stay informed about weather conditions in your area',
    todaysWeather: 'Today\'s Weather in',
    weatherDetails: 'Weather Details',
    feelsLike: 'Feels Like',
    windSpeed: 'Wind Speed',
    sevenDayForecast: 'Weekly Weather Outlook',
    weatherAlert: 'Weather Alert',
    weatherAlertDescription: 'Heavy rainfall expected in some areas. Please plan your farming activities accordingly.',
    weatherImpact: 'How Weather Affects Your Crops',
    cropPlanning: 'Planning Your Crops',
    cropPlanningDescription: 'Use this forecast to plan your sowing and harvesting schedule for better yields.',
    irrigationTitle: 'Irrigation Planning',
    irrigationDescription: 'Adjust your irrigation based on rainfall predictions to save water and protect crops.',
    harvestingTitle: 'Harvest Timing',
    harvestingDescription: 'Plan your harvest around dry spells to ensure the best quality of your produce.',
    weatherUpdated: 'Weather updated for',
    day: 'Day',
    date: 'Date',
    min: 'Min',
    max: 'Max',
    clear: 'Clear',
    clouds: 'Cloudy',
    rain: 'Rain',
    thunderstorm: 'Thunderstorm',
    mm: 'mm',
    kmh: 'km/h',
    celsius: '°C',
    riceIrrigationAdvice: 'Maintain 5cm water level in the field. Drain out excess water if any.',
    ricePestControlAdvice: 'Monitor for leaf folder and stem borer. Apply neem-based pesticides if infestation is observed.',
    riceFertilizerAdvice: 'Apply second dose of nitrogen (urea) after 3 weeks of transplanting.',
    riceBestPracticesAdvice: 'Ensure proper spacing between plants. Remove weeds regularly.',
    riceWarnings: 'Excessive rainfall may lead to flooding. Ensure proper drainage channels are maintained.',
    wheatIrrigationAdvice: 'First irrigation 20-25 days after sowing. Subsequent irrigations at intervals of 15-20 days.',
    wheatPestControlAdvice: 'Watch for aphids and rust. Apply recommended fungicides if rust appears.',
    wheatFertilizerAdvice: 'Apply nitrogen fertilizer in split doses - one at sowing and another at tillering stage.',
    wheatBestPracticesAdvice: 'Timely sowing is crucial. Prepare seedbed properly before sowing.',
    wheatWarnings: 'Frost during flowering stage can damage crops. Monitor weather forecasts closely.',
    cottonIrrigationAdvice: 'Avoid waterlogging. Irrigate at critical stages like flowering and boll development.',
    cottonPestControlAdvice: 'Monitor for bollworms and whiteflies. Use pheromone traps for pest management.',
    cottonFertilizerAdvice: 'Apply phosphorus and potassium at planting. Nitrogen in split doses.',
    cottonBestPracticesAdvice: 'Maintain optimal plant population. Practice topping to encourage branching.',
    cottonWarnings: 'Heavy rainfall during boll opening can reduce quality. Harvest promptly when ready.',
    potatoIrrigationAdvice: 'Maintain consistent soil moisture. Avoid overwatering to prevent tuber rot.',
    potatoPestControlAdvice: 'Watch for late blight. Apply copper-based fungicides as preventive measure.',
    potatoFertilizerAdvice: 'Apply potassium-rich fertilizers for better tuber development.',
    potatoBestPracticesAdvice: 'Earth up soil around plants to protect tubers from sunlight. Proper spacing is crucial.',
    potatoWarnings: 'Extended wet conditions can promote diseases. Ensure good drainage.',
    locationSettings: 'Location Settings',
    autoDetectLocation: 'Auto-detect Location',
    autoDetectDescription: 'Let the app automatically detect your location for accurate weather and market information',
    dataSettings: 'Data & Storage',
    lowDataUsage: 'Low Data (Recommended for slow internet)',
    balancedDataUsage: 'Balanced (Default)',
    highDataUsage: 'High Quality (Uses more data)',
    resetToDefaults: 'Reset to Defaults',
    hyderabad: 'Hyderabad',
    aboutMitra: 'Your trusted farming companion app that helps you make informed decisions about weather, market prices, and crop management.',
  },
  hi: {
    appName: 'मित्र',
    tagline: 'आपका कृषि साथी',
    selectCrop: 'फसल चुनें',
    selectRegion: 'क्षेत्र चुनें',
    selectSeason: 'मौसम चुनें',
    dashboard: 'डैशबोर्ड',
    marketPrices: 'बाज़ार मूल्य',
    weather: 'मौसम',
    cropAdvisory: 'फसल सलाह',
    settings: 'सेटिंग्स',
    settingsTitle: 'अपना अनुभव अनुकूलित करें',
    settingsSubtitle: 'ऐप को अपनी पसंद के अनुसार व्यक्तिगत बनाएं',
    profile: 'प्रोफ़ाइल',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    languageSettings: 'भाषा सेटिंग्स',
    languageDescription: 'अपनी पसंदीदा भाषा चुनें',
    appearance: 'दिखावट',
    light: 'हल्का',
    dark: 'गहरा',
    system: 'सिस्टम',
    notifications: 'सूचनाएं',
    weatherAlertsDescription: 'मौसम में बदलाव और पूर्वानुमान की सूचनाएं प्राप्त करें',
    priceAlerts: 'मूल्य सूचनाएं',
    priceAlertsDescription: 'फसल के मूल्य में महत्वपूर्ण बदलाव होने पर सूचनाएं प्राप्त करें',
    advisories: 'सलाह',
    advisoriesDescription: 'समय पर खेती की सलाह और सिफारिशें प्राप्त करें',
    newsUpdates: 'समाचार अपडेट',
    newsUpdatesDescription: 'कृषि समाचार और नीतियों से अपडेट रहें',
    offlineMode: 'ऑफ़लाइन मोड',
    offlineModeDescription: 'बिना इंटरनेट के महत्वपूर्ण जानकारी प्राप्त करें',
    location: 'स्थान',
    autoLocation: 'स्वचालित स्थान',
    autoLocationDescription: 'अपना स्थान स्वचालित रूप से पता करें',
    defaultLocation: 'डिफ़ॉल्ट स्थान',
    defaultLocationDescription: 'अपना पसंदीदा स्थान सेट करें',
    dataUsage: 'डेटा उपयोग',
    dataUsageDescription: 'ऐप द्वारा डेटा उपयोग को प्रबंधित करें',
    clearData: 'डेटा साफ़ करें',
    clearDataDescription: 'कैश्ड डेटा हटाएं और प्राथमिकताएं रीसेट करें',
    saveSettings: 'सेटिंग्स सहेजें',
    themeChanged: 'थीम बदलकर',
    notificationsEnabled: 'सूचनाएं सक्षम की गईं',
    offlineModeEnabled: 'ऑफ़लाइन मोड सक्षम किया गया',
    offlineModeDisabled: 'ऑफ़लाइन मोड अक्षम किया गया',
    dataClearedSuccess: 'डेटा सफलतापूर्वक साफ़ किया गया',
    settingsSaved: 'सेटिंग्स सफलतापूर्वक सहेजी गईं',
    balanced: 'संतुलित',
    highQuality: 'उच्च गुणवत्ता',
    lowData: 'कम डेटा',
    logout: 'लॉग आउट',
    language: 'भाषा',
    download: 'डाउनलोड',
    offline: 'ऑफ़लाइन एक्सेस',
    login: 'लॉग इन',
    register: 'रजिस्टर',
    phoneNumber: 'फोन नंबर',
    verifyPhone: 'फोन सत्यापित करें',
    enterOTP: 'OTP दर्ज करें',
    verifyOTP: 'OTP सत्यापित करें',
    verificationCode: 'सत्यापन कोड',
    resendOTP: 'OTP पुनः भेजें',
    otpSent: 'आपके फोन पर OTP भेजा गया है',
    verifyPhoneDescription: 'आपके फोन पर भेजा गया 6-अंक का कोड दर्ज करें',
    selectState: 'राज्य चुनें',
    todaysAdvice: 'आज की सलाह',
    dailyAdvice: 'अपने फसल की देखभाल के लिए आज पानी का छिड़काव करें।',
    welcomeBack: 'वापसी पर स्वागत है',
    helloUser: 'नमस्ते!',
    rice: 'चावल',
    wheat: 'गेहूं',
    cotton: 'कपास',
    pulses: 'दालें',
    vegetables: 'सब्जियां',
    fruits: 'फल',
    kharif: 'खरीफ',
    rabi: 'रबी',
    zaid: 'जायद',
    recentUpdates: 'हाल की अपडेट',
    loading: 'लोड हो रहा है...',
    welcomeMessage: 'मित्र में आपका स्वागत है, आपका व्यक्तिगत कृषि साथी',
    submitButton: 'जमा करें',
    mspAnnouncement: 'सरकार द्वारा खरीफ फसलों के लिए न्यूनतम समर्थन मूल्य की घोषणा',
    weatherAlert: 'मौसम चेतावनी: अगले सप्ताह पूर्वी क्षेत्रों में भारी वर्षा की संभावना',
    newTechnique: 'कृषि सम्मेलन में नई कीट प्रतिरोध तकनीक का प्रदर्शन',
    quintal: 'क्विंटल',
    mandi: 'मंडी',
    currentPrice: 'वर्तमान मूल्य',
    fromYesterday: 'कल से',
    nearbyMandis: 'नजदीकी मंडियां',
    potato: 'आलू',
    tomato: 'टमाटर',
    onion: 'प्याज',
    todayTemp: 'आज का तापमान',
    rainfall: 'वर्षा',
    humidity: 'नमी',
    forecast: 'पूर्वानुमान',
    irrigation: 'सिंचाई',
    pestControl: 'कीट नियंत्रण',
    fertilizers: 'उर्वरक',
    weatherForecast: 'मौसम का पूर्वानुमान',
    weatherDetails: 'मौसम विवरण',
    clearSkies: 'साफ आसमान और सामान्य तापमान',
    weatherUpdated: 'मौसम अपडेट हुआ',
    irrigationAdvice: 'खेत में 5 सेमी पानी का स्तर बनाए रखें। अतिरिक्त पानी होने पर निकाल दें।',
    pestControlAdvice: 'पत्ती मोड़क और तना छेदक के लिए निगरानी करें। कीट दिखने पर नीम आधारित कीटनाशकों का प्रयोग करें।',
    fertilizerAdvice: 'रोपाई के 3 सप्ताह बाद नाइट्रोजन (यूरिया) की दूसरी खुराक दें।',
    bestPracticesAdvice: 'बेहतर विकास के लिए पौधों के बीच उचित दूरी सुनिश्चित करें।',
    warnings: 'चेतावनियां',
    seasonalCalendar: 'मौसमी कैलेंडर',
    calendarComingSoon: 'कैलेंडर सुविधा जल्द आ रही है',
    expertTips: 'विशेषज्ञ सुझाव',
    soilHealth: 'मिट्टी का स्वास्थ्य',
    waterManagement: 'जल प्रबंधन',
    integratedPestManagement: 'एकीकृत कीट प्रबंधन',
    soilHealthTip: 'नियमित मिट्टी परीक्षण से पोषक तत्वों का स्तर अनुकूल रहता है',
    waterManagementTip: 'कुशल सिंचाई से पानी की बचत होती है और जलभराव से बचा जा सकता है',
    pestManagementTip: 'जब संभव हो प्राकृतिक कीट नियंत्रण विधियों का उपयोग करें',
    howToUse: 'उपयोग कैसे करें',
    howToUseStep1: 'ड्रॉपडाउन से अपनी फसल चुनें',
    howToUseStep2: 'अपना क्षेत्र चुनें',
    howToUseStep3: 'वर्तमान उगाने का मौसम चुनें',
    marketTrends: 'बाज़ार के रुझान',
    knowYourMarket: 'अपना बाज़ार जानें',
    marketInfoDescription: 'किसानों के लिए बाज़ार की गतिशीलता को समझना महत्वपूर्ण है। यहाँ जानें क्या जानना जरूरी है।',
    mandis: 'मंडियाँ',
    mandisDescription: 'कृषि बाज़ार जहाँ किसान सीधे खरीदारों को अपनी उपज बेच सकते हैं',
    priceFluctuations: 'मूल्य उतार-चढ़ाव',
    priceFluctuationsDescription: 'बाज़ार के मूल्य आपूर्ति, मांग और मौसमी कारकों के आधार पर बदलते हैं',
    msp: 'न्यूनतम समर्थन मूल्य',
    mspDescription: 'किसानों को बाज़ार की अस्थिरता से बचाने के लिए सरकार द्वारा निर्धारित चुनिंदा फसलों का न्यूनतम मूल्य',
    allCrops: 'सभी फसलें',
    noStateSelected: 'कृपया मूल्य देखने के लिए राज्य चुनें',
    majorCropsPrices: 'प्रमुख फसलों के मूल्य',
    regionalPriceComparison: 'क्षेत्रीय मूल्य तुलना',
    weeklyChanges: 'साप्ताहिक बदलाव',
    pricesUpBy: 'मूल्य में वृद्धि',
    pricesDownBy: 'मूल्य में कमी',
    perQuintal: 'प्रति क्विंटल',
    weatherForecast: 'मौसम का पूर्वानुमान',
    weatherSubtitle: 'अपने क्षेत्र के मौसम की स्थिति से अवगत रहें',
    weatherUpdated: 'मौसम अपडेट हुआ',
    weatherImpact: 'मौसम आपकी फसलों को कैसे प्रभावित करता है',
    cropPlanning: 'फसलों की योजना',
    cropPlanningDescription: 'बेहतर उपज के लिए बुवाई और कटाई की योजना बनाने के लिए इस पूर्वानुमान का उपयोग करें।',
    irrigationTitle: 'सिंचाई योजना',
    irrigationDescription: 'पानी बचाने और फसलों की रक्षा के लिए वर्षा के पूर्वानुमान के आधार पर सिंचाई समायोजित करें।',
    harvestingTitle: 'कटाई का समय',
    harvestingDescription: 'अपनी उपज की सर्वोत्तम गुणवत्ता सुनिश्चित करने के लिए सूखे मौसम के दौरान कटाई की योजना बनाएं।',
    day: 'दिन',
    date: 'तारीख',
    min: 'न्यूनतम',
    max: 'अधिकतम',
    clear: 'साफ़',
    clouds: 'बादल',
    rain: 'बारिश',
    thunderstorm: 'आंधी',
    mm: 'मिमी',
    kmh: 'किमी/घंटा',
    celsius: '°से',
    feelsLike: 'अनुभव होता है',
    windSpeed: 'हवा की गति',
    sevenDayForecast: 'साप्ताहिक मौसम का नज़ारा',
    weatherAlert: 'मौसम चेतावनी',
    weatherAlertDescription: 'कुछ क्षेत्रों में भारी वर्षा की संभावना। कृपया अपनी कृषि गतिविधियों की योजना तदनुसार बनाएं।',
    todaysWeather: 'आज का मौसम',
    forecast: 'पूर्वानुमान',
    weatherDetails: 'मौसम विवरण',
    humidity: 'नमी',
    rainfall: 'वर्षा',
    Delhi: 'दिल्ली',
    Mumbai: 'मुंबई',
    Bangalore: 'बैंगलोर',
    Kolkata: 'कोलकाता',
    Chennai: 'चेन्नई',
    cropAdvisoryTitle: 'फसल सलाह',
    cropAdvisorySubtitle: 'अपनी फसलों के लिए व्यक्तिगत सलाह प्राप्त करें',
    getAdvisory: 'सलाह प्राप्त करें',
    selectAllFields: 'कृपया सभी फील्ड चुनें',
    advisoryLoaded: 'सलाह सफलतापूर्वक लोड हुई',
    seasonalCalendar: 'मौसमी कैलेंडर',
    calendarComingSoon: 'कैलेंडर सुविधा जल्द आ रही है',
    riceIrrigationAdvice: 'खेत में 5 सेमी पानी का स्तर बनाए रखें। अतिरिक्त पानी होने पर निकाल दें।',
    ricePestControlAdvice: 'पत्ती मोड़क और तना छेदक के लिए निगरानी करें। कीट दिखने पर नीम आधारित कीटनाशकों का प्रयोग करें।',
    riceFertilizerAdvice: 'रोपाई के 3 सप्ताह बाद नाइट्रोजन (यूरिया) की दूसरी खुराक दें।',
    riceBestPracticesAdvice: 'पौधों के बीच उचित दूरी सुनिश्चित करें। नियमित रूप से खरपतवार हटाएं।',
    riceWarnings: 'अत्यधिक वर्षा से बाढ़ आ सकती है। जल निकासी चैनलों को बनाए रखें।',
    wheatIrrigationAdvice: 'बुवाई के 20-25 दिन बाद पहली सिंचाई। उसके बाद 15-20 दिन के अंतराल पर सिंचाई करें।',
    wheatPestControlAdvice: 'एफिड्स और रस्ट के लिए निगरानी करें। रस्ट दिखने पर अनुशंसित फफूंदनाशक का प्रयोग करें।',
    wheatFertilizerAdvice: 'नाइट्रोजन उर्वरक को विभाजित खुराक में दें - एक बुवाई के समय और दूसरा टिलरिंग स्टेज पर।',
    wheatBestPracticesAdvice: 'समय पर बुवाई महत्वपूर्ण है। बुवाई से पहले बीजबेड को ठीक से तैयार करें।',
    wheatWarnings: 'फूल आने के समय पाला फसल को नुकसान पहुंचा सकता है। मौसम की भविष्यवाणी पर नज़र रखें।',
    cottonIrrigationAdvice: 'जलभराव से बचें। फूल और कपास के विकास के महत्वपूर्ण चरणों में सिंचाई करें।',
    cottonPestControlAdvice: 'बॉलवर्म और सफेद मक्खी के लिए निगरानी करें। कीट प्रबंधन के लिए फेरोमोन ट्रैप का उपयोग करें।',
    cottonFertilizerAdvice: 'रोपण के समय फास्फोरस और पोटैशियम का प्रयोग करें। नाइट्रोजन विभाजित खुराक में दें।',
    cottonBestPracticesAdvice: 'इष्टतम पौध संख्या बनाए रखें। शाखाओं को बढ़ावा देने के लिए टॉपिंग का अभ्यास करें।',
    cottonWarnings: 'कपास खुलने के समय भारी वर्षा से गुणवत्ता कम हो सकती है। तैयार होने पर तुरंत कटाई करें।',
    potatoIrrigationAdvice: 'मिट्टी की नमी बनाए रखें। कंद सड़न से बचने के लिए अधिक पानी न दें।',
    potatoPestControlAdvice: 'लेट ब्लाइट के लिए निगरानी करें। निवारक उपाय के रूप में कॉपर आधारित फफूंदनाशक का प्रयोग करें।',
    potatoFertilizerAdvice: 'बेहतर कंद विकास के लिए पोटैशियम युक्त उर्वरकों का प्रयोग करें।',
    potatoBestPracticesAdvice: 'कंदों को धूप से बचाने के लिए पौधों के चारों ओर मिट्टी चढ़ाएं। उचित दूरी महत्वपूर्ण है।',
    potatoWarnings: 'लंबे समय तक नम परिस्थितियां बीमारियों को बढ़ावा दे सकती हैं। अच्छी जल निकासी सुनिश्चित करें।',
    marketPricesTitle: 'वास्तविक समय मंडी मूल्य',
    marketPricesSubtitle: 'स्थानीय मंडियों से नवीनतम फसल मूल्य प्राप्त करें',
    majorCropsPrices: 'प्रमुख फसलों के मूल्य',
    regionalPriceComparison: 'क्षेत्रीय मूल्य तुलना',
    priceFluctuations: 'मूल्य उतार-चढ़ाव',
    weeklyChanges: 'साप्ताहिक बदलाव',
    selectState: 'राज्य चुनें',
    noStateSelected: 'कृपया मूल्य देखने के लिए राज्य चुनें',
    perQuintal: 'प्रति क्विंटल',
    pricesUpBy: 'मूल्य में वृद्धि',
    pricesDownBy: 'मूल्य में कमी',
    marketTrends: 'बाज़ार के रुझान',
    knowYourMarket: 'अपना बाज़ार जानें',
    marketInfoDescription: 'किसानों के लिए बाज़ार की गतिशीलता को समझना महत्वपूर्ण है। यहाँ जानें क्या जानना जरूरी है।',
    mandis: 'मंडियाँ',
    mandisDescription: 'कृषि बाज़ार जहाँ किसान सीधे खरीदारों को अपनी उपज बेच सकते हैं',
    nearbyMandis: 'नजदीकी मंडियां',
    fromYesterday: 'कल से',
    currentPrice: 'वर्तमान मूल्य',
    // Crop names
    rice: 'चावल',
    wheat: 'गेहूं',
    cotton: 'कपास',
    pulses: 'दालें',
    potato: 'आलू',
    tomato: 'टमाटर',
    onion: 'प्याज',
    locationSettings: 'स्थान सेटिंग्स',
    autoDetectLocation: 'स्वचालित स्थान पता करें',
    autoDetectDescription: 'सटीक मौसम और बाज़ार की जानकारी के लिए ऐप को अपना स्थान स्वचालित रूप से पता करने दें',
    dataSettings: 'डेटा और स्टोरेज',
    lowDataUsage: 'कम डेटा (धीमी इंटरनेट के लिए अनुशंसित)',
    balancedDataUsage: 'संतुलित (डिफ़ॉल्ट)',
    highDataUsage: 'उच्च गुणवत्ता (अधिक डेटा का उपयोग)',
    resetToDefaults: 'डिफ़ॉल्ट पर रीसेट करें',
    hyderabad: 'हैदराबाद',
    aboutMitra: 'आपका विश्वसनीय कृषि साथी ऐप जो मौसम, बाज़ार मूल्य और फसल प्रबंधन के बारे में सूचित निर्णय लेने में आपकी मदद करता है।',
  }
};

// Provider component
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const translate = (key: string): string => {
    // First check if it's a state name
    if (stateTranslations[language]?.[key]) {
      return stateTranslations[language][key];
    }
    // Then check regular translations
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook for using language context
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};